In [1]:
import pandas as pd 
from glob import glob

In [2]:
csv = glob('dataset/*.csv')

In [3]:
csv

['dataset/BirthRate_Parsed.csv',
 'dataset/c39358a8-abf6-438a-bce3-f44979bd8de2_Data.csv',
 'dataset/BirthRate.csv',
 'dataset/c39358a8-abf6-438a-bce3-f44979bd8de2_Series - Metadata.csv']

In [4]:
_ = pd.read_csv(csv[0])

In [5]:
for i in range(len(_)):
    print(_.iloc[i])

Unnamed: 0                0
Country Name    Afghanistan
Country Code            AFG
1990                  7.466
2000                  7.485
2010                  5.977
2011                   5.77
2012                  5.562
2013                  5.359
2014                  5.163
2015                  4.976
2016                    4.8
2017                  4.633
2018                  4.473
2019                     ..
Name: 0, dtype: object
Unnamed: 0            1
Country Name    Albania
Country Code        ALB
1990              2.978
2000              2.157
2010               1.66
2011              1.673
2012              1.684
2013               1.69
2014              1.688
2015              1.677
2016              1.659
2017              1.638
2018              1.617
2019                 ..
Name: 1, dtype: object
Unnamed: 0            2
Country Name    Algeria
Country Code        DZA
1990              4.726
2000              2.514
2010               2.86
2011              2.909
2012              2.952
2013               2.99
2014              3.022
2015              3.043
2016              3.052
2017              3.045
2018              3.023
2019                 ..
Name: 2, dtype: object
Unnamed: 0                   3
Country Name    American Samoa
Country Code               ASM
1990                        ..
2000                        ..
2010                        ..
2011                        ..
2012                        ..
2013                        ..
2014                        ..
2015                        ..
2016                        ..
2017                        ..
2018                        ..
2019                        ..
Name: 3, dtype: object
Unnamed: 0            4
Country Name    Andorra
Country Code        AND
1990                 ..
2000                 ..
2010               1.27
2011                 ..
2012                 ..
2013                 ..
2014                 ..
2015                 ..
2016                 ..
2017                 ..
2018                 ..
2019                 ..
Name: 4, dtype: object
Unnamed: 0           5
Country Name    Angola
Country Code       AGO
1990             7.272
2000             6.639
2010             6.194
2011              6.12
2012             6.039
2013             5.953
2014             5.864
2015             5.774
2016             5.686
2017               5.6
2018             5.519
2019                ..
Name: 5, dtype: object
Unnamed: 0                        6
Country Name    Antigua and Barbuda
Country Code                    ATG
1990                          2.067
2000                            2.2
2010                          1.988
2011                          1.989
2012                          1.993
2013                          1.998
2014                          2.001
2015                          2.003
2016                          2.003
2017                          1.999
2018                          1.994
2019                             ..
Name: 6, dtype: object
Unnamed: 0              7
Country Name    Argentina
Country Code          ARG
1990                2.997
2000                2.542
2010                2.346
2011                2.338
2012                 2.33
2013                2.322
2014                2.312
2015                2.301
2016                2.288
2017                2.275
2018                2.261
2019                   ..
Name: 7, dtype: object
Unnamed: 0            8
Country Name    Armenia
Country Code        ARM
1990              2.544
2000              1.648
2010              1.722
2011              1.724
2012              1.725
2013              1.728
2014              1.732
2015              1.738
2016              1.744
2017               1.75
2018              1.755
2019                 ..
Name: 8, dtype: object
Unnamed: 0          9
Country Name    Aruba
Country Code      ABW
1990            2.249
2000            1.872
2010            1.768
2011            1.779
2012            1.795
2013            1.813
2014            1.834
2015            1.854
2016            1.872
2017            1.886
2018            1.896
2019               ..
Name: 9, dtype: object
Unnamed: 0             10
Country Name    Australia
Country Code          AUS
1990                1.902
2000                1.756
2010                1.928
2011                1.926
2012                 1.92
2013                1.855
2014                1.826
2015                1.814
2016                1.752
2017                1.741
2018                 1.74
2019                   ..
Name: 10, dtype: object
Unnamed: 0           11
Country Name    Austria
Country Code        AUT
1990               1.46
2000               1.36
2010               1.44
2011               1.43
2012               1.44
2013               1.44
2014               1.46
2015               1.49
2016               1.53
2017               1.52
2018               1.47
2019                 ..
Name: 11, dtype: object
Unnamed: 0              12
Country Name    Azerbaijan
Country Code           AZE
1990                  2.74
2000                     2
2010                  1.92
2011                  1.96
2012                     2
2013                  1.98
2014                  1.97
2015                  1.94
2016                   1.9
2017                  1.75
2018                  1.73
2019                    ..
Name: 12, dtype: object
Unnamed: 0                13
Country Name    Bahamas, The
Country Code             BHS
1990                    2.64
2000                   2.073
2010                   1.865
2011                   1.847
2012                   1.828
2013                    1.81
2014                   1.794
2015                   1.782
2016                   1.771
2017                   1.762
2018                   1.752
2019                      ..
Name: 13, dtype: object
Unnamed: 0           14
Country Name    Bahrain
Country Code        BHR
1990              3.732
2000              2.795
2010              2.164
2011              2.139
2012              2.118
2013              2.098
2014              2.078
2015              2.056
2016              2.033
2017               2.01
2018              1.987
2019                 ..
Name: 14, dtype: object
Unnamed: 0              15
Country Name    Bangladesh
Country Code           BGD
1990                 4.495
2000                 3.169
2010                 2.324
2011                 2.273
2012                 2.228
2013                 2.188
2014                 2.152
2015                  2.12
2016                  2.09
2017                 2.062
2018                 2.036
2019                    ..
Name: 15, dtype: object
Unnamed: 0            16
Country Name    Barbados
Country Code         BRB
1990                1.74
2000               1.775
2010               1.687
2011               1.665
2012               1.645
2013                1.63
2014                1.62
2015               1.614
2016               1.613
2017               1.615
2018               1.619
2019                  ..
Name: 16, dtype: object
Unnamed: 0           17
Country Name    Belarus
Country Code        BLR
1990              1.913
2000              1.317
2010              1.494
2011              1.515
2012               1.62
2013              1.668
2014              1.696
2015              1.724
2016              1.733
2017              1.541
2018              1.448
2019                 ..
Name: 17, dtype: object
Unnamed: 0           18
Country Name    Belgium
Country Code        BEL
1990               1.62
2000               1.67
2010               1.86
2011               1.81
2012                1.8
2013               1.76
2014               1.74
2015                1.7
2016               1.68
2017               1.65
2018               1.62
2019                 ..
Name: 18, dtype: object
Unnamed: 0          19
Country Name    Belize
Country Code       BLZ
1990             4.508
2000             3.601
2010              2.69
2011             2.638
2012             2.588
2013             2.539
2014             2.489
2015             2.439
2016             2.391
2017             2.346
2018             2.307
2019                ..
Name: 19, dtype: object
Unnamed: 0         20
Country Name    Benin
Country Code      BEN
1990            6.744
2000            5.962
2010            5.362
2011            5.305
2012            5.246
2013            5.183
2014            5.116
2015            5.047
2016            4.977
2017            4.906
2018            4.836
2019               ..
Name: 20, dtype: object
Unnamed: 0           21
Country Name    Bermuda
Country Code        BMU
1990                 ..
2000               1.74
2010               1.76
2011               1.59
2012               1.59
2013               1.63
2014               1.63
2015               1.62
2016               1.61
2017                1.6
2018                1.6
2019                 ..
Name: 21, dtype: object
Unnamed: 0          22
Country Name    Bhutan
Country Code       BTN
1990             5.493
2000             3.515
2010             2.301
2011             2.224
2012             2.159
2013             2.107
2014             2.067
2015             2.037
2016             2.014
2017             1.994
2018             1.975
2019                ..
Name: 22, dtype: object
Unnamed: 0           23
Country Name    Bolivia
Country Code        BOL
1990               4.89
2000              4.051
2010              3.213
2011              3.143
2012              3.076
2013               3.01
2014              2.947
2015              2.886
2016              2.829
2017              2.777
2018               2.73
2019                 ..
Name: 23, dtype: object
Unnamed: 0                          24
Country Name    Bosnia and Herzegovina
Country Code                       BIH
1990                             1.772
2000                             1.497
2010                             1.315
2011                             1.315
2012                             1.313
2013                             1.309
2014                             1.303
2015                             1.296
2016                             1.286
2017                             1.276
2018                             1.265
2019                                ..
Name: 24, dtype: object
Unnamed: 0            25
Country Name    Botswana
Country Code         BWA
1990               4.485
2000               3.304
2010               3.022
2011               3.017
2012               3.011
2013               3.002
2014               2.988
2015               2.968
2016               2.942
2017                2.91
2018               2.874
2019                  ..
Name: 25, dtype: object
Unnamed: 0          26
Country Name    Brazil
Country Code       BRA
1990             2.902
2000               2.3
2010             1.796
2011             1.781
2012             1.771
2013             1.764
2014             1.758
2015             1.753
2016             1.747
2017             1.739
2018              1.73
2019                ..
Name: 26, dtype: object
Unnamed: 0                          27
Country Name    British Virgin Islands
Country Code                       VGB
1990                                ..
2000                                ..
2010                                ..
2011                                ..
2012                                ..
2013                                ..
2014                                ..
2015                                ..
2016                                ..
2017                                ..
2018                                ..
2019                                ..
Name: 27, dtype: object
Unnamed: 0                     28
Country Name    Brunei Darussalam
Country Code                  BRN
1990                         3.29
2000                        2.346
2010                        1.937
2011                        1.957
2012                        1.973
2013                        1.978
2014                        1.969
2015                        1.947
2016                        1.915
2017                        1.881
2018                        1.848
2019                           ..
Name: 28, dtype: object
Unnamed: 0            29
Country Name    Bulgaria
Country Code         BGR
1990                1.82
2000                1.26
2010                1.57
2011                1.51
2012                 1.5
2013                1.48
2014                1.53
2015                1.53
2016                1.54
2017                1.56
2018                1.56
2019                  ..
Name: 29, dtype: object
Unnamed: 0                30
Country Name    Burkina Faso
Country Code             BFA
1990                   7.007
2000                   6.592
2010                   5.867
2011                   5.781
2012                   5.693
2013                   5.606
2014                   5.521
2015                   5.436
2016                   5.353
2017                   5.271
2018                   5.189
2019                      ..
Name: 30, dtype: object
Unnamed: 0           31
Country Name    Burundi
Country Code        BDI
1990              7.405
2000               6.92
2010              6.179
2011              6.088
2012              5.994
2013              5.897
2014              5.797
2015              5.697
2016              5.599
2017              5.502
2018               5.41
2019                 ..
Name: 31, dtype: object
Unnamed: 0              32
Country Name    Cabo Verde
Country Code           CPV
1990                 5.392
2000                 3.539
2010                 2.581
2011                 2.539
2012                   2.5
2013                 2.463
2014                 2.425
2015                 2.385
2016                 2.346
2017                 2.309
2018                 2.274
2019                    ..
Name: 32, dtype: object
Unnamed: 0            33
Country Name    Cambodia
Country Code         KHM
1990               5.601
2000               3.805
2010               2.875
2011               2.804
2012               2.739
2013               2.682
2014               2.633
2015               2.593
2016               2.559
2017                2.53
2018               2.503
2019                  ..
Name: 33, dtype: object
Unnamed: 0            34
Country Name    Cameroon
Country Code         CMR
1990               6.436
2000                5.58
2010               5.111
2011               5.049
2012               4.984
2013               4.916
2014               4.847
2015               4.777
2016               4.708
2017               4.639
2018               4.572
2019                  ..
Name: 34, dtype: object
Unnamed: 0          35
Country Name    Canada
Country Code       CAN
1990              1.83
2000             1.488
2010            1.6269
2011              1.61
2012            1.6142
2013             1.587
2014            1.5818
2015             1.563
2016            1.5433
2017            1.4961
2018            1.4988
2019                ..
Name: 35, dtype: object
Unnamed: 0                  36
Country Name    Cayman Islands
Country Code               CYM
1990                        ..
2000                        ..
2010                        ..
2011                        ..
2012                        ..
2013                        ..
2014                        ..
2015                        ..
2016                        ..
2017                        ..
2018                        ..
2019                        ..
Name: 36, dtype: object
Unnamed: 0                            37
Country Name    Central African Republic
Country Code                         CAF
1990                               5.811
2000                                 5.5
2010                               5.215
2011                               5.172
2012                               5.123
2013                               5.068
2014                               5.007
2015                               4.941
2016                                4.87
2017                               4.796
2018                               4.721
2019                                  ..
Name: 37, dtype: object
Unnamed: 0         38
Country Name     Chad
Country Code      TCD
1990            7.313
2000            7.354
2010            6.592
2011            6.482
2012            6.372
2013            6.262
2014            6.154
2015            6.049
2016            5.947
2017            5.846
2018            5.747
2019               ..
Name: 38, dtype: object
Unnamed: 0                   39
Country Name    Channel Islands
Country Code                CHI
1990                      1.483
2000                      1.526
2010                      1.585
2011                      1.586
2012                       1.58
2013                      1.569
2014                      1.556
2015                      1.541
2016                      1.527
2017                      1.516
2018                       1.51
2019                         ..
Name: 39, dtype: object
Unnamed: 0         40
Country Name    Chile
Country Code      CHL
1990            2.579
2000            2.055
2010            1.884
2011             1.87
2012            1.849
2013            1.821
2014            1.787
2015             1.75
2016            1.713
2017            1.678
2018            1.649
2019               ..
Name: 40, dtype: object
Unnamed: 0         41
Country Name    China
Country Code      CHN
1990            2.309
2000            1.596
2010            1.627
2011            1.632
2012            1.639
2013            1.647
2014            1.656
2015            1.665
2016            1.675
2017            1.683
2018             1.69
2019               ..
Name: 41, dtype: object
Unnamed: 0            42
Country Name    Colombia
Country Code         COL
1990               3.082
2000               2.572
2010               1.992
2011               1.958
2012                1.93
2013               1.905
2014               1.883
2015               1.863
2016               1.843
2017               1.825
2018               1.807
2019                  ..
Name: 42, dtype: object
Unnamed: 0           43
Country Name    Comoros
Country Code        COM
1990              6.412
2000              5.384
2010              4.754
2011              4.693
2012              4.628
2013              4.561
2014              4.491
2015              4.419
2016              4.347
2017              4.275
2018              4.205
2019                 ..
Name: 43, dtype: object
Unnamed: 0                    44
Country Name    Congo, Dem. Rep.
Country Code                 COD
1990                       6.746
2000                       6.751
2010                       6.544
2011                       6.493
2012                       6.432
2013                       6.363
2014                       6.287
2015                       6.203
2016                       6.112
2017                       6.017
2018                       5.919
2019                          ..
Name: 44, dtype: object
Unnamed: 0               45
Country Name    Congo, Rep.
Country Code            COG
1990                  5.119
2000                  4.871
2010                  4.765
2011                  4.742
2012                  4.712
2013                  4.676
2014                  4.634
2015                  4.587
2016                  4.536
2017                  4.482
2018                  4.428
2019                     ..
Name: 45, dtype: object
Unnamed: 0              46
Country Name    Costa Rica
Country Code           CRI
1990                 3.264
2000                 2.363
2010                 1.885
2011                 1.869
2012                 1.853
2013                 1.838
2014                 1.823
2015                 1.806
2016                 1.789
2017                 1.772
2018                 1.754
2019                    ..
Name: 46, dtype: object
Unnamed: 0                 47
Country Name    Cote d'Ivoire

In [6]:
columns = _.keys()

In [7]:
keys = list(columns[2:4])
print(keys)

['Country Code', '1990']

In [8]:
keys.extend([key[0:4] for key in list(columns[4:])])
data = []

In [9]:
for i in range(len(_)):
    k = list((_.iloc[i][2:]))
    if k[0] != float('nan'):
        data.append(k)

In [10]:
print(keys)

['Country Code', '1990', '2000', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019']

In [11]:
data[-1]

['WLD',
 '3.24847128102776',
 '2.69602080460424',
 '2.5164079871188',
 '2.49880832693411',
 '2.48938488431576',
 '2.47301858291181',
 '2.46564750799094',
 '2.45626374851034',
 '2.44557565303686',
 '2.42819623848249',
 '2.41503220525515',
 '..']

In [12]:
df = pd.DataFrame(columns=keys,data=data)

In [13]:
df

,Country Code,1990,2000,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,AFG,7.466,7.485,5.977,5.77,5.562,5.359,5.163,4.976,4.8,4.633,4.473,..
1,ALB,2.978,2.157,1.66,1.673,1.684,1.69,1.688,1.677,1.659,1.638,1.617,..
2,DZA,4.726,2.514,2.86,2.909,2.952,2.99,3.022,3.043,3.052,3.045,3.023,..
3,ASM,..,..,..,..,..,..,..,..,..,..,..,..
4,AND,..,..,1.27,..,..,..,..,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,SSF,6.34773000454864,5.75529311205185,5.25798659383723,5.19521671393123,5.12831409811247,5.05832098863271,4.98626136739344,4.91289046130586,4.83867140641079,4.76519966437033,4.69324343789147,..
260,SSA,6.34773000454864,5.75582996111249,5.25835190454332,5.19553254757593,5.12860894257978,5.05861340525604,4.98653978284398,4.91314984316163,4.83890848076443,4.76542065063241,4.69345048487193,..
261,TSS,6.34773000454864,5.75529311205185,5.25798659383723,5.19521671393123,5.12831409811247,5.05832098863271,4.98626136739344,4.91289046130586,4.83867140641079,4.76519966437033,4.69324343789147,..
262,UMC,2.62111113652418,1.89582872082814,1.84985226769867,1.85172716415791,1.86216911284928,1.86679521997225,1.87486435127454,1.88016868599821,1.88280592397843,1.87560630003226,1.87350089738021,..
263,WLD,3.24847128102776,2.69602080460424,2.5164079871188,2.49880832693411,2.48938488431576,2.47301858291181,2.46564750799094,2.45626374851034,2.44557565303686,2.42819623848249,2.41503220525515,..